can_send_node:
  ros__parameters:
    can_interface: "can0"

    roller:
      enabled: true
      topic: "/roller/can_frame"
      can_id: 0x201
      override_can_id: true

    belt:
      enable: true
      topic: "/belt/can_frame"
      can_id: 0x202
      override_can_id: true
