/belt_controller_node:
  ros__parameters:
    target_array_topic: "/vesc/target_array"
    upperbelt_logical_id: 10    #ROS2上の認識ID(上側のベルト)
    underbelt_logical_id: 11    #ROS2上の認識ID(下側のベルト)

    # レベルごとの回転数(上下で別々の回転数に設定可能)
    underbelt_level_1_rpm: 1000  # 1200  2350  4000
    underbelt_level_2_rpm: 1700  # 2000  2650  4800
    underbelt_level_3_rpm: 4900  #       3000  4900
    underbelt_level_4_rpm: 4800  #       2550  2250

    upperbelt_level_1_rpm: 1400  # 1200  2350  1000
    upperbelt_level_2_rpm: 1900  # 2000  2600  3200
    upperbelt_level_3_rpm: 800   #       3450  1000
    upperbelt_level_4_rpm: 3900  #       4900  3900
    
    # 緊急停止時のデータ配信周期
    emergency_stop_period_ms: 50
