/heading_hold_node:
  ros__parameters:
    # PID IMU
    kp: 4.0
    ki: 0.0
    kd: 0.05
    integral_limit: 0.5
    heading_deadband_rad: 0.02
    rotation_input_deadband_rad_s: 0.02
    max_correction_rad_s: 1.5

    control_period_ms: 20
    command_timeout_ms: 500
    imu_timeout_ms: 250
    command_qos_depth: 10

    raw_cmd_vel_topic: /mecanum/cmd_vel
    imu_topic: /imu/data
    corrected_cmd_vel_topic: /mecanum/cmd_vel_heading
