joy_node:
  ros__parameters:
    dev: "/dev/input/js0"

roller_controller_node:
  ros__parameters:
    rpm_topic: "/roller/rpm"
    enable_axis: 4
    enable_axis_threshold: 0.5
    stop_button: 13
    high_button: 2
    low_button: 3
    stop_rpm: 0
    high_rpm: 3000
    low_rpm: 3000

belt_controller_node:
  ros__parameters:
    enable_button: 6
    stop_button: 13
    circle_button: 1
    cross_button: 0
    triangle_button: 3
    square_button: 2
    stop_pwm: 0
    circle_pwm: 3000
    cross_pwm: 3000
    triangle_pwm: 3000
    square_pwm: 3000

roller_belt_can_packer_node:
  ros__parameters:
    can_transmit_topic: "/CAN/can0/transmit"
    stm_can_id: 0x201
    is_extended: false
    roller_rpm_topic: "/roller/rpm"
    belt_rpm_topic: "/belt/rpm"
    min_rpm: 0
    max_rpm: 3000
    publish_period_ms: 20
    timeout_ms: 500

ros2socketcan:
  ros__parameters:
    CAN_INTERFACE: "can0"
