joy_node:
  ros__parameters:
    dev: "/dev/input/js0"

roller_controller_node:
  ros__parameters:
    rpm_topic: "/roller/rpm"
    enable_axis: 3                  # L2。axis値が0.5以上で操作を有効化
    enable_axis_threshold: 0.5
    stop_button: 2                  # ○
    stop_rpm: 0
    high_button: 0                  # □
    high_rpm: 200
    low_button: 3                   # △
    low_rpm: 100

belt_controller_node:
  ros__parameters:
    rpm_topic: "/belt/rpm"
    enable_axis: 4                  # R2。axis値が0.5以上で操作を有効化
    enable_axis_threshold: 0.5
    stop_button: 2                  # ○
    stop_rpm: 0
    high_button: 0                  # □
    high_rpm: 200
    low_button: 3                   # △
    low_rpm: 100

roller_belt_can_packer_node:
  ros__parameters:
    can_transmit_topic: "/CAN/can0/transmit"
    stm_can_id: 0x201
    is_extended: false
    roller_rpm_topic: "/roller/rpm"
    belt_rpm_topic: "/belt/rpm"
    min_rpm: 0
    max_rpm: 300
    publish_period_ms: 20
    timeout_ms: 500

ros2socketcan:
  ros__parameters:
    CAN_INTERFACE: "can0"
