mecanum_odometry_node:
  ros__parameters:
    # mecanum_controller.yaml
    wheel_radius: 0.075
    robot_length: 0.355
    robot_width: 0.353
    wheel_logical_ids: [0, 1, 2, 3]  # FL, FR, RL, RR
    state_array_topic: /edulite/state_array
    odometry_topic: /wheel/odometry
    odom_frame: odom
    base_frame: base_link
    publish_period_ms: 20.0
    feedback_timeout_ms: 250.0

    # / odom
    velocity_scale_x: 1.0
    velocity_scale_y: 1.0
    velocity_scale_yaw: 1.0
    velocity_filter_alpha: 0.35  # 1.0

    # EKFIMU
    slip_compensation:
      enabled: true
      acceleration_threshold_x_m_s2: 1.0
      acceleration_threshold_y_m_s2: 0.7
      angular_acceleration_threshold_rad_s2: 2.0
      maximum_covariance_multiplier: 10.0

    pose_covariance_xy: 0.02
    pose_covariance_yaw: 0.05
    twist_covariance_xy: 0.03
    twist_covariance_yaw: 0.06

#can_imu_node:
#  ros__parameters:
#    can_topic: /socketcan_bridge/rx
#    frame_id: imu_link
#    accel_can_id: 1280
#    gyro_can_id: 1281
#    quaternion_can_id: 1282
#    accel_scale: 0.00980665
#    gyro_scale: 0.0000174532925199433
#    quaternion_scale: 0.00006103515625
#    max_component_age: 0.1

tag_localization_node:
  ros__parameters:
    detection_topic: /detection
    output_topic: /tag/pose
    map_frame: map
    base_frame: base_link
    camera_frame: camera_link
    tag_position: [0.0, 0.0, 1.0]
    tag_rpy: [0.0, 0.0, 0.0]
    covariance_xy: 0.04
    covariance_yaw: 0.08
