/stm32_driver_node:
  ros__parameters:
    imu_topic: /stm32/imu
    imu_frame_id: stm32_imu_link
    led_command_topic: "/hardware/led_cmd"
    limit_switches_topic: "/hardware/limit_switches"
    timeout_ms: 1000            # stm32のタイムアウト検知時間 (500ms -> 1000msに緩和)
    keep_alive_period_ms: 200   # heartbeatの送信と判断周期

