stm32_driver_node:
  ros__parameters:
    led_cmd_topic: "/led/cmd"              #ledのコマンドを制御ノードから受信するトピック
    limit_sw_topic: "/limit_switches"      #limitswのデータを制御ノードへ送信するトピック(std_msgs/msg/UInt8MultiArray、bitごとに1スイッチ)
    imu_topic: /imu/data
    imu_frame_id: imu_link

    #タイムアウト検知時間
    timeout_ms: 500
    #heartbeatの送信と判断周期
    keep_alive_period_ms: 100
