belt_controller_node:
  ros__parameters:
    enable_button: 7
    stop_button: 4
    circle_button: 1
    cross_button: 0
    triangle_button: 2
    square_button: 3

    stop_rpm: 0
    circle_rpm: 30
    cross_rpm: 85
    triangle_rpm: 170
    square_rpm: 255
