belt_controller_node:
  ros__parameters:
    enable_button: 7
    stop_button: 4
    circle_button: 1
    cross_button: 0
    triangle_button: 2
    square_button: 3

    stop_pwm: 0
    circle_pwm: 30
    cross_pwm: 85
    triangle_pwm: 170
    square_pwm: 255
