stm_can_send_node:
  ros__parameters:
    can_interface: "can0"
    can_id: 0x201

    roller_enabled: true
    roller_topic: "/roller/can_frame"

    belt_enabled: true
    belt_topic: "/belt/can_frame"
