spring_joy_sub:
  ros__parameters:
    subscribed_joy: /joy_second
    shoot_key: #発射キー
      type: "button"
      index: 10
    lock_key: #安全装置キー
      type: "axis"
      index: 4

spring_edulite_controller:
  ros__parameters:
    fire_speed_: -10.0     #発射時の回転速度[rad/s]
    loading_speed: -2.0  #装填時の回転速度[rad/s]
    limit_sw_index: 1   #limit_swのindex
    fire_duration: 2.0  #発射時間の長さ[s]
