name: ros2 build and test
# This workflow builds and tests ROS 2 packages using Docker Compose.
# It is triggered on push and pull request events. The workflow ensures that only one instance runs for a given branch or pull request, canceling any in-progress runs if a new one is triggered.
on:
  push:
  pull_request:

concurrency:
  group: ci-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
  
permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0

      - name: Start container
        run: |
          docker compose up -d --build

      - name: Install CI tools
        run: |
          docker compose exec -T ros2_rox2026 \
          bash -ec "
          apt update && \
          apt install -y uncrustify \
          ros-humble-ament-uncrustify && \
          pip3 install black && \
          pip3 install cmake-format"

      - name: Format C++
        run: |
          docker compose exec -T ros2_rox2026 \
          bash -ec "
            CFG=\$(find /opt/ros \
            -path "*/ament_uncrustify/configuration/ament_code_style.cfg" | head -n 1) && \
            find src \
            \( \
              -name '*.cpp' \
              -o -name '*.hpp' \
              -o -name '*.h' \
              -o -name '*.ipp' \
            \) \
            -exec uncrustify \
              -c \
              \$CFG \
              --replace \
              --no-backup \
              {} +"
                
      - name: Format Python
        run: |
          docker compose exec -T ros2_rox2026 \
          bash -ec "
            black src"

      - name: Format CMake
        run: |
          docker compose exec -T ros2_rox2026 \
          bash -ec "
            find src -name 'CMakeLists.txt' \
            -exec cmake-format --config-files .cmake-format.yml \
            --in-place {} +"

      - name: Run build
        run: |
          docker compose exec -T ros2_rox2026 \
          bash -ec " 
          source /opt/ros/humble/setup.bash && \
          cd /root/ros2_ws && \
          colcon build --symlink-install"

      # - name: Run test & test results
      #   run: |
      #     docker compose exec -T ros2_rox2026 \
      #     bash -ec " 
      #     source /opt/ros/humble/setup.bash && \
      #     cd /root/ros2_ws && \
      #     source install/setup.bash && \
      #     colcon test && \
      #     colcon test-result --verbose"

      - name: Commit formatted code
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          if ! git diff --cached --quiet
          then
            git commit -m 'style: auto format'

            BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}

            git push --force-with-lease origin HEAD:"refs/heads/$BRANCH"
          fi

      - name: Stop container
        if: always()
        run: |
          docker compose down